name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codeql:
    uses: ppizarror/workflow-actions/.github/workflows/codeql.yml@master
    with:
      language: javascript